title: Addi Darmawan # your name (or website title) here
logo: "/images/circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name is Addi Darmawan. I'm a data enthusiast, skilled in data analytics, strong analytical thinking and data visualization. I had a demonstrated history of working in the real estate industry. Welcome to my portfolio!
  <br><br>
  <a href="https://www.linkedin.com/in/addi-darmawan/">My LinkedIn Profile</a> <br>
  <a href="https://drive.google.com/file/d/10C1H2W_d5gjCtFYSQkGV3oHE_TqqN1aN/view?usp=sharing">My CV</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
